
services:
  postgresql:
    image: "postgres:latest"
    volumes:
      - database_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
volumes:
  database_volume: {}