apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: tv-back-prod
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "eljida"
        - name: DB_PASSWORD
          value: "eljid123"
        - name: DB_NAME
          value: "mydatabase"